### PR TITLE
force multiple IPs configuration without having multiple net interfaces

### PR DESCRIPTION
**Pull request by damko**
I'm not a ruby developer so, even if they are few lines, please review the code carefully

### CODE REVIEW

**Comment by mefellows** [comment]
Thanks @damko, I'll take a look at this tonight and see how we go. So in a nutshell, this basically forces the host entries to a given IP address even if Vagrant isn't the one creating them?

**Comment by damko** [comment]
You are welcome. FYI I ran some tests on my environments before PR and everything works so far.

yes. This is convenient when you have some software, like openvpn, creating network interfaces that are not handle by the virtualization software.

**Comment by mefellows** [comment]
Thanks @damko, LGTM :shipit:

**Comment by damko** [comment]
thanks to you! great plugin!

**Pull request merged**
